apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: cis-2-1-1-enable-audit-logs
spec:
  rules:
    - name: gke-audit-logging
      assert:
        all:
          - message: "GKE cluster must enable API server audit logging (logging_config.enable_components must include API_SERVER)."
            check:
              (length(planned_values.root_module.resources[?type=='google_container_cluster' && length(values.logging_config) > `0` && contains(values.logging_config[0].enable_components, 'API_SERVER')]) > `0`): true
