apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: cis-5-1-1-image-scanning
spec:
  rules:
    - name: artifact-registry-image-scanning-enabled
      assert:
        all:
          - message: "At least one Artifact Registry DOCKER repository must be provisioned for container image management."
            check:
              (length(planned_values.root_module.resources[?type=='google_artifact_registry_repository' && values.format == 'DOCKER']) > `0`): true

          - message: "Container Analysis API (containeranalysis.googleapis.com) must be enabled at the project level to enable vulnerability scanning on Artifact Registry images."
            check:
              (length(planned_values.root_module.resources[?type=='google_project_service' && values.service == 'containeranalysis.googleapis.com']) > `0`): true
