apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: cis-5-3-2-secrets-management
spec:
  rules:
    - name: external-secrets-management
      assert:
        all:
          - message: "External secrets management should be configured (Google Secret Manager integration)."
            check:
              (length(planned_values.root_module.resources[?type=='google_secret_manager_secret']) > `0`): true

          - message: "Secrets should be encrypted with customer-managed Cloud KMS keys (CMEK)."
            check:
              (length(planned_values.root_module.resources[?type=='google_kms_crypto_key']) > `0` || length(planned_values.root_module.resources[?type=='google_secret_manager_secret' && length(values.replication) > `0` && length(values.replication[0].user_managed) > `0` && length(values.replication[0].user_managed[0].replicas) > `0` && length(values.replication[0].user_managed[0].replicas[0].customer_managed_encryption) > `0` && values.replication[0].user_managed[0].replicas[0].customer_managed_encryption[0].kms_key_name != null]) > `0`): true
