apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: cis-2-1-3-audit-log-retention
spec:
  rules:
    - name: gke-audit-log-retention
      assert:
        all:
          - message: "Cloud Logging project bucket used for GKE audit logs must have retention_days >= 90."
            check:
              (length(planned_values.root_module.resources[?type=='google_logging_project_bucket_config' && values.retention_days >= `90`]) > `0`): true
