apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: custom-5.1.2
  annotations:
    policies.kyverno.io/category: CIS 5.1.2
    policies.kyverno.io/description: 'Checks for Artifact Registry access annotation or label in
      ServiceAccount or Namespace if available.

      '
    policies.kyverno.io/cel: 'true'
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: check-minimize-artifact-registry-access
    match:
      any:
      - resources:
          kinds:
          - ServiceAccount
          - Namespace
    validate:
      message: Artifact Registry access should be minimized (look for artifact-registry-access annotation or label).
      cel:
        expressions:
        - expression: (has(object.metadata.annotations) && "artifact-registry-access" in object.metadata.annotations
            && (object.metadata.annotations["artifact-registry-access"] == 'read-only')) || (has(object.metadata.labels)
            && "artifact-registry-access" in object.metadata.labels && (object.metadata.labels["artifact-registry-access"]
            == 'read-only'))
          message: Artifact Registry access should be minimized (look for artifact-registry-access annotation
            or label).
